import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // General
    appName: 'ScreenGuard Pro',
    search: 'Search',
    searchPlaceholder: 'Search by product name, model or barcode...',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    actions: 'Actions',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    currency: 'دج',
    
    // Auth
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    loginSubtitle: 'Sign in to manage your inventory',
    registerSubtitle: 'Create an account to get started',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    invalidCredentials: 'Invalid email or password',
    registerAsAdmin: 'Register as Admin',
    
    // Navigation
    dashboard: 'Dashboard',
    products: 'Products',
    addProduct: 'Add Product',
    settings: 'Settings',
    users: 'Users',
    userManagement: 'User Management',
    customers: 'Customers',
    suppliers: 'Suppliers',
    sales: 'Sales',
    pos: 'Point of Sale',
    purchases: 'Purchases',
    cashManagement: 'Cash Management',
    reports: 'Reports',
    notifications: 'Notifications',
    employees: 'Employees',
    debts: 'Debts',
    
    // Dashboard
    totalProducts: 'Total Products',
    totalUsers: 'Total Users',
    totalCustomers: 'Total Customers',
    totalSuppliers: 'Total Suppliers',
    totalEmployees: 'Total Employees',
    lowStock: 'Low Stock',
    recentProducts: 'Recent Products',
    quickStats: 'Quick Stats',
    todaySales: "Today's Sales",
    totalCash: 'Total Cash',
    totalReceivables: 'Total Receivables',
    totalPayables: 'Total Payables',
    
    // Products
    productName: 'Product Name',
    productNameEn: 'Product Name (English)',
    productNameAr: 'Product Name (Arabic)',
    description: 'Description',
    descriptionEn: 'Description (English)',
    descriptionAr: 'Description (Arabic)',
    price: 'Price',
    purchasePrice: 'Purchase Price',
    wholesalePrice: 'Wholesale Price',
    retailPrice: 'Retail Price',
    quantity: 'Quantity',
    imageUrl: 'Image URL',
    barcode: 'Barcode',
    compatibleModels: 'Compatible Models',
    compatibleModelsHelp: 'Enter phone models separated by commas',
    addNewProduct: 'Add New Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    deleteConfirm: 'Are you sure you want to delete this?',
    productAdded: 'Product added successfully',
    productUpdated: 'Product updated successfully',
    productDeleted: 'Product deleted successfully',
    noProducts: 'No products found',
    noProductsSubtitle: 'Add your first product',
    viewDetails: 'View Details',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    lowStockWarning: 'Low Stock',
    importExcel: 'Import from Excel',
    exportExcel: 'Export to Excel',
    importSuccess: 'Import completed',
    
    // Filters
    filterByModel: 'Filter by Model',
    allModels: 'All Models',
    clearFilters: 'Clear Filters',
    
    // Low Stock & OCR
    lowStockAlerts: 'Low Stock Alerts',
    lowStockThreshold: 'Low Stock Threshold',
    lowStockThresholdHelp: 'Alert when quantity falls below this',
    extractFromImage: 'Extract from Image',
    extractingModels: 'Extracting...',
    modelsExtracted: 'Models extracted',
    ocrFailed: 'Extraction failed',
    supportedFormats: 'Formats: JPG, PNG, WEBP',
    
    // Customers & Suppliers
    addCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',
    customerName: 'Customer Name',
    phone: 'Phone',
    address: 'Address',
    notes: 'Notes',
    totalPurchases: 'Total Purchases',
    balance: 'Balance',
    noCustomers: 'No customers found',
    customerAdded: 'Customer added',
    customerUpdated: 'Customer updated',
    customerDeleted: 'Customer deleted',
    addSupplier: 'Add Supplier',
    editSupplier: 'Edit Supplier',
    supplierName: 'Supplier Name',
    noSuppliers: 'No suppliers found',
    supplierAdded: 'Supplier added',
    supplierUpdated: 'Supplier updated',
    supplierDeleted: 'Supplier deleted',
    
    // POS / Sales
    newSale: 'New Sale',
    addToCart: 'Add to Cart',
    cart: 'Cart',
    emptyCart: 'Cart is empty',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    paidAmount: 'Paid Amount',
    remaining: 'Remaining',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    bank: 'Bank',
    wallet: 'E-Wallet',
    completeSale: 'Complete Sale',
    printInvoice: 'Print Invoice',
    saleCompleted: 'Sale completed',
    invoiceNumber: 'Invoice Number',
    selectCustomer: 'Select Customer',
    walkInCustomer: 'Walk-in Customer',
    scanBarcode: 'Scan Barcode',
    returnSale: 'Return Sale',
    saleReturned: 'Sale returned',
    newPurchase: 'New Purchase',
    selectSupplier: 'Select Supplier',
    purchaseCompleted: 'Purchase completed',
    
    // Cash Management
    cashBox: 'Cash Box',
    bankAccount: 'Bank Account',
    eWallet: 'E-Wallet',
    transfer: 'Transfer',
    transferFunds: 'Transfer Funds',
    fromBox: 'From',
    toBox: 'To',
    amount: 'Amount',
    transferCompleted: 'Transfer completed',
    transactions: 'Transactions',
    income: 'Income',
    expense: 'Expense',
    
    // Status
    paid: 'Paid',
    partial: 'Partial',
    unpaid: 'Unpaid',
    returned: 'Returned',
    pending: 'Pending',
    overdue: 'Overdue',
    
    // Employees
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    employeeName: 'Employee Name',
    position: 'Position',
    salary: 'Salary',
    hireDate: 'Hire Date',
    commissionRate: 'Commission Rate',
    noEmployees: 'No employees found',
    employeeAdded: 'Employee added',
    employeeUpdated: 'Employee updated',
    employeeDeleted: 'Employee deleted',
    attendance: 'Attendance',
    recordAttendance: 'Record Attendance',
    present: 'Present',
    absent: 'Absent',
    late: 'Late',
    leave: 'Leave',
    advances: 'Advances',
    addAdvance: 'Add Advance',
    totalAdvances: 'Total Advances',
    totalCommission: 'Total Commission',
    
    // Debts
    addDebt: 'Add Debt',
    receivables: 'Receivables',
    payables: 'Payables',
    dueDate: 'Due Date',
    debtAmount: 'Debt Amount',
    payDebt: 'Pay Debt',
    debtPaid: 'Debt payment recorded',
    noDebts: 'No debts found',
    schedulePayment: 'Schedule Payment',
    
    // Reports
    salesChart: 'Sales Chart',
    topProducts: 'Top Products',
    topCustomers: 'Top Customers',
    profitReport: 'Profit Report',
    totalRevenue: 'Total Revenue',
    totalCost: 'Total Cost',
    grossProfit: 'Gross Profit',
    profitMargin: 'Profit Margin',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    
    // Backup
    backup: 'Backup',
    createBackup: 'Create Backup',
    backupCreated: 'Backup created',
    
    // Notifications
    markAsRead: 'Mark as Read',
    markAllRead: 'Mark All as Read',
    noNotifications: 'No notifications',
    restockAlert: 'Restock Alert',
    lowStockAlert: 'Low Stock Alert',
    
    // Errors
    error: 'Error',
    somethingWentWrong: 'Something went wrong',
    tryAgain: 'Try Again',
    notFound: 'Not Found',
    unauthorized: 'Unauthorized',
    forbidden: 'Access Denied',
    
    // User Management
    allUsers: 'All Users',
    userRole: 'Role',
    userEmail: 'Email',
    userName: 'Name',
    changeRole: 'Change Role',
    deleteUser: 'Delete User',
    deleteUserConfirm: 'Delete this user?',
    userDeleted: 'User deleted',
    userUpdated: 'User updated',
    noUsers: 'No users found',
    adminRole: 'Admin',
    userRoleLabel: 'User',
    cannotDeleteSelf: 'Cannot delete yourself',
    createdAt: 'Created At',
    
    // Product Families
    productFamilies: 'Product Families',
    addFamily: 'Add Family',
    editFamily: 'Edit Family',
    familyName: 'Family Name',
    familyNameEn: 'Family Name (English)',
    familyNameAr: 'Family Name (Arabic)',
    parentFamily: 'Parent Family',
    noParent: 'No Parent (Main Family)',
    familyAdded: 'Family added',
    familyUpdated: 'Family updated',
    familyDeleted: 'Family deleted',
    noFamilies: 'No families found',
    productCount: 'Product Count',
    cannotDeleteFamilyWithProducts: 'Cannot delete family with products',
    cannotDeleteFamilyWithChildren: 'Cannot delete family with sub-families',
    selectFamily: 'Select Family',
    allFamilies: 'All Families',
    
    // API Keys
    apiKeys: 'API Keys',
    addApiKey: 'Add API Key',
    keyName: 'Key Name',
    keyType: 'Key Type',
    internal: 'Internal',
    external: 'External',
    service: 'Service',
    endpointUrl: 'Endpoint URL',
    permissions: 'Permissions',
    read: 'Read',
    write: 'Write',
    keyValue: 'Key Value',
    secretValue: 'Secret Value',
    keyPreview: 'Key Preview',
    generateKey: 'Generate Key',
    copyKey: 'Copy Key',
    keyCopied: 'Key copied to clipboard',
    keyActive: 'Active',
    keyInactive: 'Inactive',
    toggleKey: 'Toggle Key',
    lastUsed: 'Last Used',
    noApiKeys: 'No API keys found',
    apiKeyAdded: 'API key added',
    apiKeyDeleted: 'API key deleted',
    
    // Recharge / Top-up
    recharge: 'Recharge',
    topUp: 'Top-up',
    mobileRecharge: 'Mobile Recharge',
    operator: 'Operator',
    phoneNumber: 'Phone Number',
    rechargeType: 'Recharge Type',
    credit: 'Credit',
    internet: 'Internet',
    flexy: 'Flexy',
    ussdCode: 'USSD Code',
    rechargeAmount: 'Recharge Amount',
    selectOperator: 'Select Operator',
    selectAmount: 'Select Amount',
    rechargeNow: 'Recharge Now',
    rechargeSuccess: 'Recharge completed',
    rechargeHistory: 'Recharge History',
    todayRecharges: 'Today Recharges',
    totalProfit: 'Total Profit',
    noRecharges: 'No recharges found',
    copyUssd: 'Copy USSD Code',
    ussdCopied: 'USSD code copied',
    
    // Delivery
    delivery: 'Delivery',
    deliveryService: 'Delivery Service',
    withDelivery: 'With Delivery',
    withoutDelivery: 'Without Delivery',
    deliveryAddress: 'Delivery Address',
    deliveryWilaya: 'Wilaya',
    deliveryCity: 'City/Commune',
    deliveryFee: 'Delivery Fee',
    homeDelivery: 'Home Delivery',
    officeDelivery: 'Office Delivery',
    selectWilaya: 'Select Wilaya',
    
    // Credit Sale
    creditSale: 'Credit Sale',
    sellOnCredit: 'Sell on Credit',
    paymentType: 'Payment Type',
    cashPayment: 'Cash Payment',
    creditPayment: 'On Credit',
    partialPayment: 'Partial Payment',
    customerDebt: 'Customer Debt',
    customerDebts: 'Customer Debts',
    totalDebt: 'Total Debt',
    payDebt: 'Pay Debt',
    debtAmount: 'Debt Amount',
    debtHistory: 'Debt History',
    noDebt: 'No Debt',
    addPayment: 'Add Payment',
    debtPaid: 'Debt Payment Recorded',
    viewDebts: 'View Debts',
    customerRequired: 'Please select a customer for credit sale',
    
    // SMS Reminders
    smsReminders: 'SMS Reminders',
    sendReminder: 'Send Reminder',
    sendBulkReminder: 'Send to All',
    smsSettings: 'SMS Settings',
    smsLogs: 'SMS History',
    smsTemplate: 'Message Template',
    selectTemplate: 'Select Template',
    customMessage: 'Custom Message',
    autoReminder: 'Auto Reminder',
    reminderFrequency: 'Reminder Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    reminderDay: 'Reminder Day',
    reminderTime: 'Reminder Time',
    minDebtAmount: 'Minimum Debt Amount',
    smsSent: 'SMS Sent',
    smsFailed: 'SMS Failed',
    sendingReminders: 'Sending reminders...',
    remindersSent: 'Reminders sent successfully',
    noCustomersSelected: 'Please select customers',
    smsProvider: 'SMS Provider',
    providerMocked: 'Simulated (Not Connected)',
  },
  ar: {
    // General
    appName: 'سكرين جارد برو',
    search: 'بحث',
    searchPlaceholder: 'ابحث باسم المنتج أو الموديل أو الباركود...',
    loading: 'جاري التحميل...',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    actions: 'الإجراءات',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    currency: 'دج',
    
    // Auth
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    name: 'الاسم',
    welcomeBack: 'مرحباً بعودتك',
    createAccount: 'إنشاء حساب جديد',
    loginSubtitle: 'سجل دخولك لإدارة المخزون',
    registerSubtitle: 'أنشئ حساباً للبدء',
    noAccount: 'ليس لديك حساب؟',
    hasAccount: 'لديك حساب بالفعل؟',
    invalidCredentials: 'البريد أو كلمة المرور غير صحيحة',
    registerAsAdmin: 'التسجيل كمدير',
    
    // Navigation
    dashboard: 'لوحة التحكم',
    products: 'المنتجات',
    addProduct: 'إضافة منتج',
    settings: 'الإعدادات',
    users: 'المستخدمين',
    userManagement: 'إدارة المستخدمين',
    customers: 'الزبائن',
    suppliers: 'الموردين',
    sales: 'المبيعات',
    pos: 'نقطة البيع',
    purchases: 'المشتريات',
    cashManagement: 'إدارة المال',
    reports: 'التقارير',
    notifications: 'الإشعارات',
    employees: 'العمال',
    debts: 'الديون',
    
    // Dashboard
    totalProducts: 'إجمالي المنتجات',
    totalUsers: 'إجمالي المستخدمين',
    totalCustomers: 'إجمالي الزبائن',
    totalSuppliers: 'إجمالي الموردين',
    totalEmployees: 'إجمالي العمال',
    lowStock: 'مخزون منخفض',
    recentProducts: 'أحدث المنتجات',
    quickStats: 'إحصائيات سريعة',
    todaySales: 'مبيعات اليوم',
    totalCash: 'إجمالي النقد',
    totalReceivables: 'إجمالي المستحقات',
    totalPayables: 'إجمالي الديون',
    
    // Products
    productName: 'اسم المنتج',
    productNameEn: 'اسم المنتج (إنجليزي)',
    productNameAr: 'اسم المنتج (عربي)',
    description: 'الوصف',
    descriptionEn: 'الوصف (إنجليزي)',
    descriptionAr: 'الوصف (عربي)',
    price: 'السعر',
    purchasePrice: 'سعر الشراء',
    wholesalePrice: 'سعر الجملة',
    retailPrice: 'سعر التجزئة',
    quantity: 'الكمية',
    imageUrl: 'رابط الصورة',
    barcode: 'الباركود',
    compatibleModels: 'الموديلات المتوافقة',
    compatibleModelsHelp: 'أدخل الموديلات مفصولة بفواصل',
    addNewProduct: 'إضافة منتج جديد',
    editProduct: 'تعديل المنتج',
    deleteProduct: 'حذف المنتج',
    deleteConfirm: 'هل أنت متأكد من الحذف؟',
    productAdded: 'تمت إضافة المنتج',
    productUpdated: 'تم تحديث المنتج',
    productDeleted: 'تم حذف المنتج',
    noProducts: 'لا توجد منتجات',
    noProductsSubtitle: 'أضف أول منتج',
    viewDetails: 'عرض التفاصيل',
    inStock: 'متوفر',
    outOfStock: 'غير متوفر',
    lowStockWarning: 'مخزون منخفض',
    importExcel: 'استيراد من Excel',
    exportExcel: 'تصدير إلى Excel',
    importSuccess: 'تم الاستيراد بنجاح',
    
    // Filters
    filterByModel: 'تصفية حسب الموديل',
    allModels: 'جميع الموديلات',
    clearFilters: 'مسح الفلاتر',
    
    // Low Stock & OCR
    lowStockAlerts: 'تنبيهات المخزون المنخفض',
    lowStockThreshold: 'حد المخزون المنخفض',
    lowStockThresholdHelp: 'تنبيه عندما تقل الكمية عن هذا',
    extractFromImage: 'استخراج من صورة',
    extractingModels: 'جاري الاستخراج...',
    modelsExtracted: 'تم الاستخراج',
    ocrFailed: 'فشل الاستخراج',
    supportedFormats: 'الصيغ: JPG, PNG, WEBP',
    
    // Customers & Suppliers
    addCustomer: 'إضافة زبون',
    editCustomer: 'تعديل الزبون',
    customerName: 'اسم الزبون',
    phone: 'الهاتف',
    address: 'العنوان',
    notes: 'ملاحظات',
    totalPurchases: 'إجمالي المشتريات',
    balance: 'الرصيد',
    noCustomers: 'لا يوجد زبائن',
    customerAdded: 'تمت إضافة الزبون',
    customerUpdated: 'تم تحديث الزبون',
    customerDeleted: 'تم حذف الزبون',
    addSupplier: 'إضافة مورد',
    editSupplier: 'تعديل المورد',
    supplierName: 'اسم المورد',
    noSuppliers: 'لا يوجد موردين',
    supplierAdded: 'تمت إضافة المورد',
    supplierUpdated: 'تم تحديث المورد',
    supplierDeleted: 'تم حذف المورد',
    
    // POS / Sales
    newSale: 'بيع جديد',
    addToCart: 'أضف للسلة',
    cart: 'السلة',
    emptyCart: 'السلة فارغة',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    total: 'الإجمالي',
    paidAmount: 'المبلغ المدفوع',
    remaining: 'المتبقي',
    paymentMethod: 'طريقة الدفع',
    cash: 'نقداً',
    bank: 'بنك',
    wallet: 'محفظة إلكترونية',
    completeSale: 'إتمام البيع',
    printInvoice: 'طباعة الفاتورة',
    saleCompleted: 'تم البيع',
    invoiceNumber: 'رقم الفاتورة',
    selectCustomer: 'اختر الزبون',
    walkInCustomer: 'عميل نقدي',
    scanBarcode: 'مسح الباركود',
    returnSale: 'إرجاع البيع',
    saleReturned: 'تم الإرجاع',
    newPurchase: 'شراء جديد',
    selectSupplier: 'اختر المورد',
    purchaseCompleted: 'تم الشراء',
    
    // Cash Management
    cashBox: 'الصندوق النقدي',
    bankAccount: 'الحساب البنكي',
    eWallet: 'المحفظة الإلكترونية',
    transfer: 'تحويل',
    transferFunds: 'تحويل أموال',
    fromBox: 'من',
    toBox: 'إلى',
    amount: 'المبلغ',
    transferCompleted: 'تم التحويل',
    transactions: 'الحركات المالية',
    income: 'دخل',
    expense: 'مصروف',
    
    // Status
    paid: 'مدفوع',
    partial: 'جزئي',
    unpaid: 'غير مدفوع',
    returned: 'مرتجع',
    pending: 'معلق',
    overdue: 'متأخر',
    
    // Employees
    addEmployee: 'إضافة عامل',
    editEmployee: 'تعديل العامل',
    employeeName: 'اسم العامل',
    position: 'المنصب',
    salary: 'الراتب',
    hireDate: 'تاريخ التوظيف',
    commissionRate: 'نسبة العمولة',
    noEmployees: 'لا يوجد عمال',
    employeeAdded: 'تمت إضافة العامل',
    employeeUpdated: 'تم تحديث العامل',
    employeeDeleted: 'تم حذف العامل',
    attendance: 'الحضور',
    recordAttendance: 'تسجيل الحضور',
    present: 'حاضر',
    absent: 'غائب',
    late: 'متأخر',
    leave: 'إجازة',
    advances: 'السلف',
    addAdvance: 'إضافة سلفة',
    totalAdvances: 'إجمالي السلف',
    totalCommission: 'إجمالي العمولات',
    
    // Debts
    addDebt: 'إضافة دين',
    receivables: 'مستحقات (ديون على الزبائن)',
    payables: 'ديون (للموردين)',
    dueDate: 'تاريخ الاستحقاق',
    debtAmount: 'مبلغ الدين',
    payDebt: 'سداد الدين',
    debtPaid: 'تم تسجيل السداد',
    noDebts: 'لا توجد ديون',
    schedulePayment: 'جدولة السداد',
    
    // Reports
    salesChart: 'مخطط المبيعات',
    topProducts: 'أفضل المنتجات',
    topCustomers: 'أفضل الزبائن',
    profitReport: 'تقرير الأرباح',
    totalRevenue: 'إجمالي الإيرادات',
    totalCost: 'إجمالي التكلفة',
    grossProfit: 'صافي الربح',
    profitMargin: 'هامش الربح',
    last7Days: 'آخر 7 أيام',
    last30Days: 'آخر 30 يوم',
    
    // Backup
    backup: 'النسخ الاحتياطي',
    createBackup: 'إنشاء نسخة احتياطية',
    backupCreated: 'تم إنشاء النسخة',
    
    // Notifications
    markAsRead: 'تحديد كمقروء',
    markAllRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد إشعارات',
    restockAlert: 'تنبيه إعادة تخزين',
    lowStockAlert: 'تنبيه مخزون منخفض',
    
    // Errors
    error: 'خطأ',
    somethingWentWrong: 'حدث خطأ ما',
    tryAgain: 'حاول مرة أخرى',
    notFound: 'غير موجود',
    unauthorized: 'غير مصرح',
    forbidden: 'الوصول مرفوض',
    
    // User Management
    allUsers: 'جميع المستخدمين',
    userRole: 'الدور',
    userEmail: 'البريد الإلكتروني',
    userName: 'الاسم',
    changeRole: 'تغيير الدور',
    deleteUser: 'حذف المستخدم',
    deleteUserConfirm: 'حذف هذا المستخدم؟',
    userDeleted: 'تم حذف المستخدم',
    userUpdated: 'تم تحديث المستخدم',
    noUsers: 'لا يوجد مستخدمين',
    adminRole: 'مدير',
    userRoleLabel: 'مستخدم',
    cannotDeleteSelf: 'لا يمكن حذف حسابك',
    createdAt: 'تاريخ الإنشاء',
    
    // Product Families
    productFamilies: 'عائلات المنتجات',
    addFamily: 'إضافة عائلة',
    editFamily: 'تعديل العائلة',
    familyName: 'اسم العائلة',
    familyNameEn: 'اسم العائلة (إنجليزي)',
    familyNameAr: 'اسم العائلة (عربي)',
    parentFamily: 'العائلة الأم',
    noParent: 'بدون (عائلة رئيسية)',
    familyAdded: 'تمت إضافة العائلة',
    familyUpdated: 'تم تحديث العائلة',
    familyDeleted: 'تم حذف العائلة',
    noFamilies: 'لا توجد عائلات',
    productCount: 'عدد المنتجات',
    cannotDeleteFamilyWithProducts: 'لا يمكن حذف عائلة تحتوي منتجات',
    cannotDeleteFamilyWithChildren: 'لا يمكن حذف عائلة تحتوي عائلات فرعية',
    selectFamily: 'اختر العائلة',
    allFamilies: 'جميع العائلات',
    
    // API Keys
    apiKeys: 'مفاتيح API',
    addApiKey: 'إضافة مفتاح API',
    keyName: 'اسم المفتاح',
    keyType: 'نوع المفتاح',
    internal: 'داخلي',
    external: 'خارجي',
    service: 'الخدمة',
    endpointUrl: 'رابط الخدمة',
    permissions: 'الصلاحيات',
    read: 'قراءة',
    write: 'كتابة',
    keyValue: 'قيمة المفتاح',
    secretValue: 'المفتاح السري',
    keyPreview: 'معاينة المفتاح',
    generateKey: 'إنشاء مفتاح',
    copyKey: 'نسخ المفتاح',
    keyCopied: 'تم نسخ المفتاح',
    keyActive: 'نشط',
    keyInactive: 'غير نشط',
    toggleKey: 'تبديل الحالة',
    lastUsed: 'آخر استخدام',
    noApiKeys: 'لا توجد مفاتيح API',
    apiKeyAdded: 'تمت إضافة المفتاح',
    apiKeyDeleted: 'تم حذف المفتاح',
    
    // Recharge / Top-up
    recharge: 'شحن الرصيد',
    topUp: 'شحن',
    mobileRecharge: 'شحن رصيد الهاتف',
    operator: 'المشغل',
    phoneNumber: 'رقم الهاتف',
    rechargeType: 'نوع الشحن',
    credit: 'رصيد',
    internet: 'أنترنت',
    flexy: 'فليكسي',
    ussdCode: 'كود USSD',
    rechargeAmount: 'مبلغ الشحن',
    selectOperator: 'اختر المشغل',
    selectAmount: 'اختر المبلغ',
    rechargeNow: 'اشحن الآن',
    rechargeSuccess: 'تم الشحن بنجاح',
    rechargeHistory: 'سجل الشحن',
    todayRecharges: 'شحن اليوم',
    totalProfit: 'إجمالي الربح',
    noRecharges: 'لا توجد عمليات شحن',
    copyUssd: 'نسخ كود USSD',
    ussdCopied: 'تم نسخ الكود',
    
    // Delivery
    delivery: 'التوصيل',
    deliveryService: 'خدمة التوصيل',
    withDelivery: 'مع التوصيل',
    withoutDelivery: 'بدون توصيل',
    deliveryAddress: 'عنوان التوصيل',
    deliveryWilaya: 'الولاية',
    deliveryCity: 'البلدية/المدينة',
    deliveryFee: 'رسوم التوصيل',
    homeDelivery: 'توصيل للمنزل',
    officeDelivery: 'توصيل للمكتب',
    selectWilaya: 'اختر الولاية',
    
    // Credit Sale
    creditSale: 'البيع بالدين',
    sellOnCredit: 'بيع بالدين',
    paymentType: 'نوع الدفع',
    cashPayment: 'نقداً',
    creditPayment: 'دين',
    partialPayment: 'دفع جزئي',
    customerDebt: 'دين الزبون',
    customerDebts: 'ديون الزبائن',
    totalDebt: 'إجمالي الدين',
    payDebt: 'سداد الدين',
    debtAmount: 'مبلغ الدين',
    debtHistory: 'سجل الديون',
    noDebt: 'لا يوجد دين',
    addPayment: 'إضافة دفعة',
    debtPaid: 'تم تسجيل دفعة الدين',
    viewDebts: 'عرض الديون',
    customerRequired: 'يرجى اختيار زبون للبيع بالدين',
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'ar');
  const isRTL = language === 'ar';
  const t = translations[language];
  
  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.body.dir = isRTL ? 'rtl' : 'ltr';
  }, [language, isRTL]);
  
  const toggleLanguage = () => setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
